<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Options */
?>

<?php $options = $this->getOptionList(); ?>
<?php if ($options): ?>
<div class="truncated">
  <div class="truncated_full_value">
      <div class="item-options">
          <p><?php echo $this->__('Options Details'); ?></p>
          <dl>
              <?php foreach ($options as $option): ?>
              <dt><?php echo $this->escapeHtml($option['label']) ?></dt>
              <dd>
                  <?php if (is_array($option['value'])): ?>
                  <?php echo nl2br(implode("\n", $option['value'])) ?>
                  <?php else: ?>
                  <?php echo $option['value'] ?>
                  <?php endif; ?>
              </dd>
              <?php endforeach; ?>
          </dl>
      </div>
  </div>
  <a href="#" onclick="return false;" class="details"><?php echo $this->__('View Details') ?></a>
</div>
<?php endif ?>
