<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<div id="mini-wishlist-disabled">
	<div class="mini-header">
	</div>
	<div class="mini-content">
		<p class="block-subtitle">There are no items in your wishlist *</p>
		<div class="clear"></div>
	</div>
	<div class="mini-footer">
		<p>Remember to login to use this feature.</p>
	</div>
</div>