<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>

<ol>
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <?php if ($_item->getCount() > 0): ?>
        <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>" id="cat-filter-<?php echo $_item->getName() ?>">
			<?php echo $_item->getLabel() ?>
			<span class="item-count"><?php echo '  ('.$_item->getCount().')' ?></span>
		</a>
        <?php else:?>
		<p>
			<?php echo $_item->getLabel() ?>
			<span class="item-count"><?php echo '  ('.$_item->getCount().')' ?></span>
		</p>
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ol>
