<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<div id="mini-care">
	<div class="mini-header">
		<?php echo $this->__('Call us on: 086568846') ?>
	</div>
	<div class="mini-content">
		<p class="block-subtitle"><?php echo $this->__('Explore menu') ?></p>
		<div id="customer-care-menu">
			<a>Customer Service</a>
			<a>Delivery Information</a>
			<a>About Our Shop</a>
			<a>Shop Security</a>
			<a>Terms & Conditions</a>
			<a>Privacy Policy</a>
			<a>Returns</a>
			<a>Contacts</a>
		</div>
		<div class="clear"></div>
	</div>
	<div class="mini-footer">
		<p>Useful info to be placed here.</p>
	</div>
</div>