<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<div class="page-title">
    <h1><?php echo Mage::helper('customer')->__('You are now logged out') ?></h1>
</div>
<h3>
	<p><img class="a-center" src="<?php echo $this->getSkinUrl('images/slides-js/loading-small.gif') ?>" /></p>
	<?php echo Mage::helper('customer')->__('You have signed out and will be redirected to our homepage in 5 seconds.') ?>
</h3>



<script type="text/javascript">
//<![CDATA[
    setTimeout(function(){ location.href = '<?php echo $this->getUrl() ?>'},5000);
//]]>
</script>

