<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<div class="col2-set">
    <div class="box">
        <div class="box-title">
            <h3><?php echo $this->__('Address Book') ?></h3>
            <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
        </div>
        <div class="box-content">
            <div class="col-1">
                <h4><?php echo $this->__('Default Billing Address') ?></h4>
                <address>
                    <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
                    <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </address>
            </div>
            <div class="col-2">
                <h4><?php echo $this->__('Default Shipping Address') ?></h4>
                <address>
                    <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
                    <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </address>
            </div>
        </div>
    </div>
</div>
