<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
 
/* @var $this Mage_Catalog_Block_Product_Compare_Sidebar */
?>
<?php 
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
?>
<div class="block block-list block-compare">
    <div class="block-title">
        <strong><span><?php echo $this->__('Compare Products') ?>
            <?php if($_helper->getItemCount() > 0): ?> 
                <small><?php echo $this->__(' %d ', $_helper->getItemCount()) ?></small>
            <?php endif; ?>
        </span></strong>
    </div>
    <div class="block-content">
    <?php if($_helper->getItemCount() > 0): ?>
		<ol id="compare-items">
		
			<?php foreach($this->helper('catalog/product_compare')->getItemCollection() as $_index=>$_item): ?>
			
			<li class="item">
			<input type="hidden" value="<?php echo $_item->getId() ?>" />
				<a href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>');"><?php echo $this->__('Remove This Item') ?></a>
				
				<?php if ($this->helper('wishlist')->isAllow()) : ?>
					<a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist" ><?php echo $this->__('Add to Wishlist') ?></a>
				<?php endif; ?>
				
				<?php /* if($_item->isAvailable()): <- Not working, looking for workaround, although all products by default are enabled, if not, you would not have the chance to add them to compare list or to see in catalog */ ?>
				<a href="<?php echo $_helper->getAddToCartUrl($_item) ?>" title="<?php echo $this->__('Add to Cart') ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a>
				<?php /* endif; */ ?>
				
				<a class="product-image" href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init(Mage::getModel('catalog/product')->load($_item->getId()), 'small_image')->resize(180, 180) ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" height="180" width="180" /></a>
				
                <!--Product name -->
				<p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
				<!-- -->
			</li>
			<?php endforeach; ?>
		</ol>
        <!--<script type="text/javascript">decorateList('compare-items')</script>-->
        <div class="actions">
            <a href="<?php echo $_helper->getClearListUrl() ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>');"><?php echo $this->__('Clear All') ?></a>
            <button type="button" title="<?php echo $this->__('Compare') ?>" class="button" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span><?php echo $this->__('Compare') ?></span></span></button>
        </div>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items to compare.') ?></p>
    <?php endif; ?>
    </div>
</div>
