<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php /* @var $this Mage_Sales_Block_Recurring_Profile_View */?>
<?php if ($this->getIsAddress()):?>

<?php foreach ($this->getRenderedInfo() as $row):?>
<address><?php echo nl2br($this->escapeHtml($this->getObjectData($row, 'value')))?></address>
<?php endforeach;?>

<?php else:?>

<table class="info-table">
    <tbody>
        <?php foreach ($this->getRenderedInfo() as $row):?>
        <?php $isAmount = $this->getObjectData($row, 'is_amount');?>
        <tr>
            <th><?php echo $this->escapeHtml($this->getObjectData($row, 'label'))?>:</th>
            <td><?php echo $this->renderRowValue($row) ?></td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<?php endif;?>
