<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<div class="checkout-method">
	<div class="col2-set">
		<?php echo $this->getChildHtml('login_before')?>
		<div class="col-1">
			<h3><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
		</div>
		<div class="col-2">
			<h3><?php echo $this->__('Already registered?') ?></h3>
			<h4><?php echo $this->__('Please log in below:') ?></h4>
		</div>
	</div>
	<div class="col2-set">
		<div class="col-1">
			<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
				<ul class="form-list opc-method">
					<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
					<li class="control">
						<input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
					</li>
					<?php endif; ?>
					<li class="control">
						<input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
					</li>
				</ul>
			<?php else: ?>
				<ul class="form-list">
					<li class="control">
						<input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
					</li>
				</ul>
			<?php endif; ?>
		</div>
		<div class="col-2">
			<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
			<form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
			<fieldset>
				<ul class="form-list opc-login">
					<li>
						<label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
						<div class="input-box">
							<input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
						</div>
					</li>
					<li>
						<label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
						<div class="input-box">
							<input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
						</div>
					</li>
					<li class="required"><?php echo $this->__('* Required Fields') ?></li>
					<li><a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="forgot-password"><?php echo $this->__('Forgot your password?') ?></a></li>
				</ul>
			</fieldset>
			</form>
		</div>
	</div>
	<div class="col2-set">
		<div class="col-1">
			<div class="buttons-set">
				<button type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?></span></span></button>
			</div>
		</div>
		<div class="col-2">
			<div class="buttons-set">
				<button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Sign In') ?></span></span></button>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
</script>
