<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if($this->getItemCount()): ?>
<div class="crosssell">
    <h2><?php echo $this->__('We also recommend') ?></h2>
    <ul id="crosssell-products-list">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item">
            <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(80); ?>" width="80" height="80" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
            <div class="product-details">
                <h4 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h4>
                <?php echo $this->getPriceHtml($_item, true) ?>
                <div class="select-add-to">
					<select onchange="setLocation(this.value)">
						<option>Add to:</option>
						<option value="<?php if ($this->helper('wishlist')->isAllow()) : ?><?php echo $this->getAddToWishlistUrl($_item) ?><?php endif; ?>">Wishlist</option>
						<option value="<?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?><?php echo $_compareUrl ?><?php endif; ?>">Compare</option>
						<option value="<?php echo $this->getAddToCartUrl($_item) ?>">Cart</option>
					</select>
				</div>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>
