<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<div class="box-account box-tags">
    <div class="box-head">
        <h2><?php echo $this->__('My Recent Tags') ?></h2>
        <a href="<?php echo $this->getAllTagsUrl() ?>"><?php echo $this->__('View All Tags') ?></a>
    </div>
    <ol id="my_recent_tags">
        <?php $iterator = 0; ?>
        <?php foreach( $this->getCollection()->getItems() as $_item ): ?>
            <li class="item">
                <span class="number"><?php echo ++$iterator ?></span>
                <div class="details">
                    <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h3>
                    <div class="tags">
                        <strong><?php echo $this->__('Tags:') ?></strong>
                        <?php $_i = 0; ?>
                        <ul>
                        <?php foreach( $_item->getProductTags() as $_tag ): ?>
                            <li><a href="<?php echo $_tag->getViewTagUrl() ?>"><?php echo $this->htmlEscape($_tag->getName()) ?></a><?php if(++$_i != sizeof($_item->getProductTags()->getItems())): ?>,<?php endif; ?></li>
                        <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('my_recent_tags', 'none-recursive');</script>
</div>
