<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */

/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
	
	<?php /* Retrieve gallery images */ ?>
	
	<?php if (count($this->getGalleryImages()) > 0): ?>
	<div class="product-gallery">
		<div class="slides_container">
			<?php /* Get default image first */ ?>
			<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
				<a href="#">
					<?php
						$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(360).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" width="360" height="360" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
						echo $_helper->productAttribute($_product, $_img, 'image');
					?>
				</a href="#">
			<?php else: ?>
				<a href="#">
					<?php
						$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(360).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" width="360" height="360" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
						echo $_helper->productAttribute($_product, $_img, 'image');
					?>
				</a href="#">
			<?php endif; ?>
			<?php /* Next get gallery images */ ?>
			<?php foreach ($this->getGalleryImages() as $_image): ?>
				<a href="#" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
					<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(360); ?>" width="360" height="360" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
				</a>
			<?php endforeach; ?>
		</div>
		
		<ul class="pagination">
			<?php /* Get thumbnail of default image */ ?>
			<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
			<li>
				<a href="#">
					<?php
						$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'thumbnail')->resize(80).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" width="80" height="80" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
						echo $_helper->productAttribute($_product, $_img, 'image');
					?>
				</a>
			</li>
			<?php else: ?>
			<li>
				<a href="#">
					<?php
						$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'thumbnail')->resize(80).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" width="80" height="80" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
						echo $_helper->productAttribute($_product, $_img, 'image');
					?>
				</a>
			</li>
			<?php endif; ?>
			<?php /* Get rest thumbnails */ ?>
			<?php foreach ($this->getGalleryImages() as $_image): ?>
				<li>
					<a href="#" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
						<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(80); ?>" width="80" height="80" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
					</a>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
	
	<?php /* If no gallery images get default image */ ?>	
	<?php else: ?>
	
	<div class="product-gallery">
		<div class="slides_container">
			<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
			<a>
				<?php
					$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(360).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" width="360" height="360" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				?>
			</a>
			<?php else: ?>
			<a>
				<?php
					$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(360).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" width="360" height="360" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
					echo $_helper->productAttribute($_product, $_img, 'image');
				?>
			</a>
			<?php endif; ?>
		</div>
	</div>
	
	<?php endif; ?>






