<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
 
/**
 * @deprecated  after 1.4.0.0-alpha3
 */
?>
<div class="price-box" id="product_price">
    <p class="old-price"><?php echo $this->__('Was:') ?> <?php echo $this->getPrice() ?></p>
    <p class="special-price"><?php echo $this->getPrice() ?></p>
</div>
