<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php /* @var $this Mage_Sales_Block_Recurring_Profiles */ ?>
<div class="page-title">
    <h1><?php echo $this->__('Recurring Profiles') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="recurring-profiles">

    <?php echo $this->getChildHtml('grid')?>

    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
</div>
