<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

	<h2 class="title"><?php echo $this->__('About theme') ?></h2>
	
	<div id="promo1" class="mini-slider">
		
    	<ul class="slides_container">
					
            <li class="promo-slide">
                <a href="#" title="#" class=""><img src="<?php echo $this->getSkinUrl('images/media/promo1a.png') ?>" width="220" height="280" alt="User friendly theme" /></a>
			</li>
			<li class="promo-slide">
                <a href="#" title="#" class=""><img src="<?php echo $this->getSkinUrl('images/media/promo1b.png') ?>" width="220" height="280" alt="Many color combinations" /></a>
			</li>
			<li class="promo-slide">
                <a href="#" title="#" class=""><img src="<?php echo $this->getSkinUrl('images/media/promo1c.png') ?>" width="220" height="280" alt="User guide" /></a>
			</li>
			
		</ul><!-- end slides_container -->
	</div>
