<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */
?>
<?php if(count($this->getStores())>1): ?>
<div class="form-language">
    <label for="select-language"><?php echo $this->__('Your Language:') ?></label>
    <select id="select-language" title="<?php echo $this->__('Your Language') ?>" onchange="window.location.href=this.value">
    <?php foreach ($this->getStores() as $_lang): ?>
        <?php $_selected = ($_lang->getId() == $this->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
        <option value="<?php echo $_lang->getCurrentUrl() ?>"<?php echo $_selected ?>><?php echo $this->htmlEscape($_lang->getName()) ?></option>
    <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>
