<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php if( $this->getCollection() && $this->count()): ?>
<div class="box-account box-reviews">
    <div class="box-head">
        <h2><?php echo $this->__('My Recent Reviews') ?></h2>
        <a href="<?php echo $this->getAllReviewsUrl() ?>"><?php echo $this->__('View All Reviews') ?></a>
    </div>
    <ol id="my_recent_reviews">
    <?php $iterator = 0 ?>
    <?php foreach ($this->getCollection() as $_review): ?>
        <li class="item">
            <span class="number"><?php echo ++$iterator ?></span>
            <div class="details">
                <h3 class="product-name"><a href="<?php echo $this->getReviewUrl($_review->getReviewId()) ?>"><?php echo $this->htmlEscape($_review->getName()) ?></a></h3>
                <?php if($_review->getSum()): ?>
                    <div class="ratings">
                        <strong><?php echo $this->__('Rating:') ?></strong>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('my_recent_reviews');</script>
</div>
<?php endif; ?>
