<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>


<div class="page-title category-title">
    <h1><?php echo 'All Active Products' ?></h1>
</div>



<?php
	/*
		Following code works only when you have extended category layer view block. 
		You should change protected function _prepareLayout()
			FROM
			 $categoryBlock = $this->getLayout()->createBlock($this->_categoryBlockName)
				->setLayer($this->getLayer())
				->init();
			TO
			 $categoryBlock = $this->getLayout()->createBlock($this->_categoryBlockName)
				->setLayer($this->getLayer()->getCurrentCategory()->setIsAnchor(1))
				->init();
		Only then you will be able to load all store products in a layer
		Thanks to - EcommerceDeveloper
	*/
	
	$layer = Mage::getSingleton('catalog/layer');
	$layer->getCurrentCategory()->setIsAnchor(1); /* sets root category of current store */
	$_productCollection = $layer->getProductCollection();
	$_productCollection->addAttributeToFilter('status',1); /* 0 or 1 */
	$_productCollection->addAttributeToFilter('visibility',4); /* 1.2.3.4 */
	$_productCollection->addAttributeToSelect('*');
	$_helper = $this->helper('catalog/output');
	
	
?>

<div id="catalog-view">

	<?php if(!$_productCollection->count()): /* If we don't have any products to show */ ?>
		<p class="note-msg"><?php echo $this->__('There are no active or visible products to show.') ?></p>
		
	<?php else: ?>
		<div class="category-products">
			<?php // Get layered navigation block ?>
			<?php echo $this->getChildHtml('topfilter') ?>
			
			<?php echo $this->getToolbarHtml() ?>
			
			<?php // List mode ?>
			<?php if($this->getMode()!='grid'): ?>
			<?php $_iterator = 0; ?>
			<ol class="products-list" id="products-list">
			<?php foreach ($_productCollection as $_product): ?>
				<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
					<?php // Product Image ?>
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
					<?php // Product description ?>
					<div class="product-shop">
						<div class="f-fix">
							<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
							<?php if($_product->getRatingSummary()): ?>
							<?php echo $this->getReviewsSummaryHtml($_product, short /* template type */ , false /* if is visible when no reviews found */ )?>
							<?php endif; ?>
							<div class="desc std">
								<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
							</div>
							<div class="list-item-details">
								<?php echo $this->getPriceHtml($_product, true) ?>
								<div class="actions">
									<!-- Adding dropdown links -->
									<div class="select-add-to">
										<select onchange="setLocation(this.value)">
											<option>Add to:</option>
											<option value="<?php if ($this->helper('wishlist')->isAllow()) : ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>">Wishlist</option>
											<option value="<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?><?php echo $_compareUrl ?><?php endif; ?>">Compare</option>
											
											<?php if($_product->isSaleable()): ?>
											<option value="<?php echo $this->getAddToCartUrl($_product) ?>">Cart</option>
											<?php endif; ?>
										</select>
									</div>
									<div class="add_to_cart_button">
										<?php if($_product->isSaleable()): ?>
											<button type="button" title="<?php echo $this->__('Buy') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Buy') ?></span></span></button>
										<?php else: ?>
											<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
										<?php endif; ?>
									</div>
									<div class="clear"></div>
								</div>
								<div class="clear"></div>
							</div>
						</div>
						<div class="clear"></div>
					</div>
				</li>
			<?php endforeach; ?>
			</ol>

			<?php else: ?>

			<?php // Grid Mode ?>

			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $this->getColumnCount(); ?>
			<?php $i=0; foreach ($_productCollection as $_product): ?>
				<?php if ($i++%$_columnCount==0): ?>
				<ul class="products-grid">
				<?php endif ?>
					<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(215); ?>" width="200" height="200" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
						<div class="item_description_box">
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
							<?php if($_product->getRatingSummary()): ?>
							<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							<?php endif; ?>
							<div class="price_and_actions">
								<?php echo $this->getPriceHtml($_product, true) ?>
								
								<div class="select-add-to">
									<select onchange="setLocation(this.value)">
										<option>Add to:</option>
										<option value="<?php if ($this->helper('wishlist')->isAllow()) : ?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif; ?>">Wishlist</option>
										<option value="<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?><?php echo $_compareUrl ?><?php endif; ?>">Compare</option>
										
										<?php if($_product->isSaleable()): ?>
										<option value="<?php echo $this->getAddToCartUrl($_product) ?>">Cart</option>
										<?php endif; ?>
									</select>
								</div>
							</div>
							<div class="add_to_cart_button">
								<?php if($_product->isSaleable()): ?>
									<button type="button" title="<?php echo $this->__('Buy') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Buy') ?></span></span></button>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
								
							</div>
						</div>
					</li>
				<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
				</ul>
				<?php endif ?>
				<?php endforeach ?>
			
			<?php endif; ?>
			
			<div class="toolbar-bottom">
				<?php echo $this->getToolbarHtml() ?>
			</div>
		</div>
	<?php endif ?>
</div>