<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
/**
 * categories menu for store
 *
 * @see boomboom_navigation_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php
/**
<?php $_menu = $this->renderCategoriesMenuHtml(1, 'outermost', 'childrenwrap') ?>
<?php if($_menu): ?>
<?php foreach( $this->getStoreCategories() as $_category ){
	echo $this->drawItem($_category); }
?>
<?php endif ?>
**/
?>
<?php $_menu = $this->renderCategoriesMenuHtml() ?>
<?php if($_menu): ?>
<div class="block block-navigation">
    <div class="block-title"><strong><span><?php echo $this->__('Categories') ?></span></strong></div>
    <div class="block-content">
        <ul id="nav-sidebox">
        <?php echo $_menu ?>
        </ul>
    </div>
</div>
<?php endif ?>