<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<div class="error-image">
	<img src="<?php echo $this->getSkinUrl('images/media/404.png') ?>" title="error 404 - page not found" alt="error 404 - page not found" />
</div>

<img src="<?php echo $this->getSkinUrl('images/media/fly.png') ?>" title="I am FLY" alt="" id="fly" />

<div class="error-options">
	<p class="description">If you typed the URL directly, please make sure the spelling is correct.<br /><br />If you clicked on a link to get here, the link is outdated.</p>
	<p class="links">
		<a href="<?php echo $this->getUrl('/') ?>">Home</a>
		<a href="<?php echo $this->getUrl('shoppage') ?>">Shop</a>
		<a href="<?php echo $this->getUrl('customer/account') ?>">Account</a>
	</p>
	<div class="clear"></div>
</div>