<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<div class="subscribe">
	<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
		<div class="form-subscribe">
			<label for="newsletter"><?php echo $this->__('Subscribe to our newsletter') ?></label>
			<div class="input-box">
			   <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Enter your e-mail address here') ?>" class="input-text required-entry validate-email" />
			</div>
			<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
		</div>
	</form>
	<script type="text/javascript">
	//<![CDATA[
		var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
		new Varien.searchForm('newsletter-validate-detail', 'newsletter', '<?php echo $this->helper('newsletter')->__('Enter your email address') ?>');
	//]]>
	</script>
</div>