<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
    $_item = $this->getItem();
    $isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
?>
<li class="item">
    <?php if ($this->hasProductUrl()): ?>
        <a href="<?php echo $this->getProductUrl()?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(80, 80)->setWatermarkSize('30x10'); ?>" width="80" height="80" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></a>
    <?php else: ?>
        <span class="product-image"><img src="<?php echo $this->getProductThumbnail()->resize(80, 80)->setWatermarkSize('30x10'); ?>" width="80" height="80" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /></span>
    <?php endif; ?>
    <div class="product-details">
        <a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?') ?>');" class="btn-remove"><?php echo $this->__('Remove This Item') ?></a>
        <?php if ($isVisibleProduct): ?>
        <a href="<?php echo $this->getConfigureUrl() ?>" title="<?php echo $this->__('Edit item') ?>" class="btn-edit"><?php echo $this->__('Edit item')?></a>
        <?php endif ?>
        <p class="product-name"><?php if ($this->hasProductUrl()): ?><a href="<?php echo $this->getProductUrl() ?>"><?php endif; ?><?php echo $this->htmlEscape($this->getProductName()) ?><?php if ($this->hasProductUrl()): ?></a><?php endif; ?></p>
        <p class="product-qty">Qty: <span><?php echo $this->getQty() ?></span></p>

			<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
				<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
					<?php echo $this->__('Excl. Tax'); ?>:
				<?php endif; ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
					<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
				<?php else: ?>
					<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
				<?php endif; ?>
				<?php if (Mage::helper('weee')->getApplied($_item)): ?>
					<br />
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
						<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
						<?php endforeach; ?>
						</small>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
						<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
						<?php endforeach; ?>
						</small>
					<?php endif; ?>
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
					<?php endif; ?>
				<?php endif; ?>
			<?php endif; ?>



			<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
				<?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
				<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
					<br /><?php echo $this->__('Incl. Tax'); ?>:
				<?php endif; ?>
				<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales')): ?>
					<?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
				<?php else: ?>
					<?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
				<?php endif; ?>
				<?php if (Mage::helper('weee')->getApplied($_item)): ?>
					<br />
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales')): ?>
						<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
						<?php endforeach; ?>
						</small>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales')): ?>
						<small>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
						<?php endforeach; ?>
						</small>
					<?php endif; ?>
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales')): ?>
						<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
					<?php endif; ?>
				<?php endif; ?>
			<?php endif; ?>
	
        <?php if ($_options = $this->getOptionList()):?>
			<p class="has-more"><?php echo $this->__('Details') ?>
				<span><?php echo $this->__('More details visible in cart') ?></span>
			</p>
			<!--
			<div class="truncated">
				<a href="#" onclick="return false;" class="details"><?php echo $this->__('Details') ?></a>
				<div class="truncated_full_value">
					<dl class="item-options">
						<?php foreach ($_options as $_option) : ?>
						<dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
						<dd>
							<?php if (is_array($_option['value'])): ?>
							<?php echo nl2br(implode("\n", $_option['value'])) ?>
							<?php else: ?>
							<?php echo $_option['value'] ?>
							<?php endif; ?>
						</dd>
						<?php endforeach; ?>
					</dl>
				</div>
			</div>
			-->
        <?php endif; ?>
    </div>
	<div class="clear"></div>
</li>
