<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php if ($this->getOrderHasDownloadable()): ?>
    <?php echo Mage::helper('downloadable')->__('Go to <a href="%s">My Downloadable Products</a>', $this->getDownloadableProductsUrl()) ?>
<?php endif; ?>
