<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<?php $_product = $this->getProduct(); ?>
<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()); ?>
<?php if ($_product->isSaleable()):?>
    <?php if (count($_options)): ?>
        <dl>
        <?php foreach ($_options as $_option): ?>
            <?php if (!$_option->getSelections()): ?>
                <?php continue; ?>
            <?php endif; ?>
            <?php echo $this->getOptionHtml($_option) ?>
        <?php endforeach; ?>
        </dl>
    <?php else: ?>
        <p><?php echo $this->__('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
