<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<h3 class="product-name"><a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a></h3>
<?php if ($_options = $this->getOptionList()):?>
<dl class="item-options">
    <?php foreach ($_options as $_option) : ?>
    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
    <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
    <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
        <?php if (isset($_formatedOptionValue['full_view'])): ?>
        <div class="truncated_full_value">
            <dl class="item-options">
                <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
            </dl>
        </div>
        <?php endif; ?>
    </dd>
    <?php endforeach; ?>
</dl>
<?php endif; ?>
