<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<div class="page-title">
        <h1><?php echo $this->__('Order Success') ?></h1>
    </div>
<div class="multiple-checkout">
    
    <h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>
    <p><?php echo $this->__('We are processing your order and you will soon receive an email with details of the order. Once the order has shipped you will receive another email with a link to track its progress.') ?></p>
    <?php if($_orderIds = $this->getOrderIds()): ?>
    <p>
        <?php $flag = false ?>
        <?php echo $this->__('Your order number is ') ?>
        <?php foreach ($_orderIds as $orderId=>$incrementId): ?>
            <?php if ($flag): ?>
                <?php echo ', ' ?>
            <?php endif; ?>
            <?php $flag = true ?>
            <a href="<?php echo $this->getViewOrderUrl($orderId) ?>"><?php echo $incrementId ?></a>
        <?php endforeach; ?>
    </p>
    <?php endif; ?>
    <?php echo $this->getChildHtml() ?>
    <div class="buttons-set">
        <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button" onclick="setLocation('<?php echo $this->getContinueUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
    </div>
</div>
