<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<div class="footer-container">

	<div class="footer">
	
		<div class="grid_2">
		
			<h3>Privacy</h3>
			<ul>
				<li><a href="#">Privacy policy</a></li> <!-- Simple link example -->
				<li><a href="#">Terms of use</a></li>
				<li><a href="#">Fur policy</a></li>
				<li><a href="#">The truth about coupons</a></li>
			</ul>
			<div class="copyright-info">
				<?php echo $this->getCopyright() ?> <!-- Lets get copyright info from backend -->
			</div>
			
		</div>
		
		<div class="grid_2">
		
			<h3>Customer care</h3>
			<ul>
				<li><a href="#">Contacts info</a></li> <!-- Simple link example -->
				<li><a href="#">Returns</a></li>
				<li><a href="#">Shipping</a></li>
				<li><a href="#">FAQ's</a></li>
				<li><a href="#">Customer service center</a></li>
				<li><a href="#">Safe shopping guarantee</a></li>
				<li><a href="#">Secure shopping</a></li>
			</ul>
		</div>
		
		<div class="grid_2">
		
			<h3>About</h3>
			<?php echo $this->getChildHtml('cms_footer_links') ?> <!-- Lets get footer links block from backend -->
			<ul>
				<li><a href="#">Jobs</a></li> <!-- Simple link example -->
				<li><a href="#">Customer testimonials</a></li>
				<li><a href="#">The warehouses</a></li>
				<li><a href="#">Don't ever click here</a></li>
			</ul>
			
		</div>
		
		<div class="grid_2">
			
			<h3>More stuff</h3>
			<ul>
				<li><a href="#">Measurment guide</a></li> <!-- Simple link example -->
				<li><a href="#">Model measurments</a></li>
				<li><a href="#">Size convertion chart</a></li>
			</ul>
			
			<h3>We are social</h3>
			<ul>
				<li><a href="#">Youtube</a></li> <!-- Simple link example -->
				<li><a href="#">Facebook</a></li>
				<li><a href="#">Twitter</a></li>
			</ul>
			
		</div>
		
		<div class="grid_4">
			<?php echo $this->getChildHtml('newsletter') ?> <!-- Lets get subscribe block -->
			<img src="<?php echo $this->getSkinUrl('images/media/why-subscribe.png') ?>" alt="Subscribe value" title="Subscribe value" />
		</div>
			
		<div class="clear"></div> <!-- Clear floated elements, it is not needed in this case, but just in case somebody will add and float something -->
		
		<br /><!-- add extra space -->

		
		
		<div class="grid_10 inline-links ">
		
			<?php echo $this->getChildHtml('footer_links') ?> <!-- Lets get default Magento links -->
			
		</div>
		
		<div class="grid_2 ">
		
			Design: <a href="http://www.ivarprudnikov.com" target="blank" title="Visit my portfolio site">ivarPrudnikov</a> <!-- Small tag -->
			
		</div>

		<div class="clear"></div> <!-- Clear floated elements, it is not needed in this case, but just in case somebody will add and float something -->
		
    </div>
	
</div>