<?php
/**
 * Boomboom for Magento 1.5.1.0
 * Made by Shildek (http://shildek.com)
 * Distributed by ThemeForest (http://themeforest.net)
 *
 * @author     Aivaras Prudnikovas
 * @package    default_boomboom
 * @copyright  Copyright 2011 Aivaras Prudnikovas (http://ivarprudnikov.com)
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
/**
 * @see Mage_Page_Block_Html_Notices
 */
?>
<?php if ($this->displayNoscriptNotice()): ?>
    <noscript>
        <div class="noscript">
            <div class="noscript-inner">
                <p><strong><?php echo $this->__('JavaScript seem to be disabled in your browser.'); ?></strong></p>
                <p><?php echo $this->__('You must have JavaScript enabled in your browser to utilize the functionality of this website.'); ?></p>
            </div>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($this->displayDemoNotice()): ?>
    <p class="demo-notice"><?php echo $this->__('System is under maintenance. Any orders placed through this store will not be honored or fulfilled.') ?></p>
<?php endif; ?>
